Resonance.Insight3.Web/ViewModels/Reporting/ReportsDataModel.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Resonance.Insight3.Web.ViewModels.Reporting
{
    public class ReportsViewModel
    {
        public string ServerEndpoint { get; set; }
        public string Account { get; set; }
        public string Application { get; set; }
        public string ReportName { get; set; }
        public string ReportDisplayName { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public string ReportUri { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }

        public List<SelectListItem> ApplicationList { get; set; }
    }
}

Resonance.Insight3.Web/ViewModels/Reporting/ReportsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Resonance.Insight3.Web.ViewModels.Reporting
{
    public class ReportsViewModel
    {
        private DateTime _endDate;

        public string ServerEndpoint { get; set; }
        public string Account { get; set; }
        public string Application { get; set; }
        public string ReportName { get; set; }
        public string ReportDisplayName { get; set; }
        public string AppID { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate
        {
            set { _endDate = value; }

            get
            {
                if (_endDate > DateTime.Today.AddDays(-1))
                {
                    _endDate = DateTime.Today.AddDays(-1);
                }
                return _endDate;
            }
        }
        public string ReportUri { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string ReportHtml { get; set; }
        public List<string> Recommendations { get; set; }
        public List<string> Segments { get; set; }
        public List<string> Strategies { get; set; } 
        public List<string> ApplicationList { get; set; }
    }
}

Resonance.Insight3.Web/ViewModels/Reporting/TrendsViewModel.cs
using System;
using System.Collections.Generic;
using Resonance.Insight3.Web.CertonaService;

namespace Resonance.Insight3.Web.ViewModels.Reporting
{
    public class TrendsViewModel
    {
        private DateTime _endDate;

        public string ChartName { get; set; }
        public string Title { get; set; }        
        public DateTime StartDate { get; set; } 

        public DateTime EndDate
        {
            set { _endDate = value; }
            
            get
            {
                if (_endDate > DateTime.Today.AddDays(-1))
                {
                    _endDate = DateTime.Today.AddDays(-1);
                }
                return _endDate;
            }
        }

        public string ID { get; set; }
        public List<TrendSeries> TrendSeries { get; set; }
        public NodeType NodeType { get; set; }
        public DateTime? ReportingLastUpdated { get; set; }
        public IEnumerable<string> SeriesColors
        {
            get
            {
                var seriesColors = new List<string>();
                seriesColors.Add("#0095EE");
                seriesColors.Add("#0012F1");
                seriesColors.Add("#FFBB00");
                seriesColors.Add("#00F177");
                seriesColors.Add("#FF8C00");
                seriesColors.Add("#FF3D00");
                seriesColors.Add("#FF6BC8");
                seriesColors.Add("#21F000");
                seriesColors.Add("#6FC4F7");
                seriesColors.Add("#D281B3");
                seriesColors.Add("#2D37B4");
                seriesColors.Add("#7079F8");
                seriesColors.Add("#BF9930");
                seriesColors.Add("#FFDA73");
                seriesColors.Add("#2DB570");
                seriesColors.Add("#70F8B3");
                seriesColors.Add("#A65B00");
                seriesColors.Add("#FFA940");
                seriesColors.Add("#A62800");
                seriesColors.Add("#FF9473");
                seriesColors.Add("#FFAEE1");
                seriesColors.Add("#A62375");
                seriesColors.Add("#82F86F");
                seriesColors.Add("#3FB42D");
                return seriesColors;
            }
        }
    }

    public class TrendSeries
    {
        public string Group { get; set; }
        public string Category { get; set; }
        public double? Data { get; set; }
    }
}

Resonance.Insight3.Web/Controllers/ReportingController.cs
using System;
using System.Web.Mvc;
using Resonance.Insight3.Web.CertonaService;
using Resonance.Insight3.Web.Models;

namespace Resonance.Insight3.Web.Controllers
{
    public class ReportingController : Controller
    {
        public PartialViewResult ViewReport(NodeDTO node)
        {
            string cultureName = null;
            if (HttpContext != null && HttpContext.Request != null && HttpContext.Request.UserLanguages != null && HttpContext.Request.UserLanguages.Length > 0)
                cultureName = HttpContext.Request.UserLanguages[0];
        
            var model = ReportingModel.GetReportViewModel();
            return PartialView(model);
        }

        [HttpGet]
        public string GetReportData(int startYear,
            int startMonth,
            int startDay,
            int endYear,
            int endMonth,
            int endDay,
            string nodeId,
            string appId,
            //string segmentId,
            string schemeId,
            string strategy)
        {
            var startDate = new DateTime(startYear, startMonth, startDay);
            var endDate = new DateTime(endYear, endMonth, endDay);

            string cultureName = null;
            if (HttpContext != null && HttpContext.Request != null && HttpContext.Request.UserLanguages != null && HttpContext.Request.UserLanguages.Length > 0)
                cultureName = HttpContext.Request.UserLanguages[0];

            //var htmlReport = Convert.ToString(ReportingModel.GetReportDataModel(startDate, endDate, nodeId, appId, schemeId, cultureName, strategy));
            var htmlReport = Convert.ToString(ReportingModel.GetReportDataModel(startDate, endDate, nodeId, appId, cultureName, strategy));
            return htmlReport;
        }

        /*
        [HttpGet]
        public JsonResult GetRecommendations(string applicationId)
        {
            var model = ReportingModel.GetRecommendations(applicationId);
            return Json(model.Recommendations, JsonRequestBehavior.AllowGet);
        }
        */ 

        [HttpGet]
        public JsonResult GetUserAccountApplicationFeatures()
        {
            var model = ReportingModel.GetUserAccountApplicationFeatures();
            return Json(model.ApplicationList, JsonRequestBehavior.AllowGet);
        }

        /*
        [HttpGet]
        public JsonResult GetSegments(string applicationId)
        {
            var model = ReportingModel.GetSegments(applicationId);
            return Json(model.Segments, JsonRequestBehavior.AllowGet);
        }
        */ 

        [HttpGet]
        public JsonResult GetStrategies(string applicationId)
        {
            var model = ReportingModel.GetStrategies(applicationId);
            return Json(model.Strategies, JsonRequestBehavior.AllowGet);
        }

        public PartialViewResult ViewTrends()
        {
            return PartialView();
        }

        [HttpGet]
        public JsonResult GetTrendsData(int startYear, int startMonth, int startDay, int endYear, int endMonth, int endDay, string ID, NodeType nodeType)
        {
            var model = ReportingModel.RefreshTrends(startYear, startMonth, startDay, endYear, endMonth, endDay, ID, nodeType);
            return Json(model.TrendSeries, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetTrendsModel(int startYear, int startMonth, int startDay, int endYear, int endMonth, int endDay, string ID, NodeType nodeType)
        {
            var model = ReportingModel.RefreshTrends(startYear, startMonth, startDay, endYear, endMonth, endDay, ID, nodeType);
            return Json(model.TrendSeries);
        }
    }
}

Resonance.Insight3.Web/Views/Reporting/ViewReport.cshtml
@model Resonance.Insight3.Web.ViewModels.Reporting.ReportsViewModel
@using Resonance.Insight3.Web.Helpers

@{
    var showallrecommendationstrategies = this.LocalResources("showallrecommendationstrategies");
    var showallactiverecommendationstrategies = this.LocalResources("showallactiverecommendationstrategies");
    var showallbutdeletedrecommendation = this.LocalResources("showallbutdeletedrecommendation");
    //var allsegments = this.LocalResources("allsegments");
    //var allrecommendationboxes = this.LocalResources("allrecommendationboxes");
    //var allschemes = this.LocalResources("allschemes");
}

<script type="text/javascript">
    var nodeId = $("#NodeID").val();
    var recommendedAssets = 3;
    var strategyComparison = 4;
    
    $("#Submit").click(function () {
        refreshReport();
    });

    function refreshReport() {
        var startDate = new Date($("#StartDate").val());
        var endDate = new Date($("#EndDate").val());
        //var segmentId = $("#SegmentId").val();
        //var schemeId = $("#RecBoxId").val();
        var yesterday = new Date();
        var appId = $("#AppID").val();
        var strategy = $("#Strategy").val();
        
        if (appId == "") {
            appId = '@Model.ApplicationList.FirstOrDefault()';
        }

        yesterday.setDate(yesterday.getDate() - 1);

        @*
        if (schemeId == "") {
            schemeId = '@allschemes';
        }

        
        if (segmentId == "") {
            segmentId = '@allsegments';
        }
        *@

        
        if (strategy == "") {
            strategy = '@showallactiverecommendationstrategies';
        }
        
        
        if (endDate > yesterday) {
            ShowsysMessage("error", "The <i>To Date</i> must be no later than yesterday's date.");
            return (false);
        }

        if (startDate <= endDate) {
            var startYear = startDate.getFullYear();
            var startMonth = startDate.getMonth() + 1; // 0 based
            var startDay = startDate.getDate();

            var endYear = endDate.getFullYear();
            var endMonth = endDate.getMonth() + 1; // 0 based
            var endDay = endDate.getDate();
            
            $.ajax({
                url: "@Url.Action("GetReportData","Reporting")",
                cache: false,
                type: 'GET',
                data: {
                    startYear: startYear,
                    startMonth: startMonth,
                    startDay: startDay,
                    endYear: endYear,
                    endMonth: endMonth,
                    endDay: endDay,
                    nodeID: nodeId,
                    appId: appId,
                    //segmentId: segmentId,
                    //schemeId: schemeId,
                    strategy: strategy
                },
                success: function (data) {
                    $("#ViewReport").html(data);
                }
            });
        }
    }

    function startChange() {
        var endPicker = $("#EndDate").data("kendoDatePicker"),
            startDate = this.value();

        if (startDate) {
            startDate = new Date(startDate);
            startDate.setDate(startDate.getDate());
            endPicker.min(startDate);
        }
    }

    function endChange() {
        var startPicker = $("#StartDate").data("kendoDatePicker"),
            endDate = this.value();

        if (endDate) {
            endDate = new Date(endDate);
            endDate.setDate(endDate.getDate() - 1);
            startPicker.max(endDate);
        }
    }

    function ApplicationChange() {
        var appId = $("#AppID").val();
        
        @*
        if (nodeId == recommendedAssets || nodeId == strategyComparison) {
            $.getJSON('@Url.Action("GetSegments","Reporting")', { applicationId: appId }, function (data) {
                data: 
                    var items = [];

                items.push({ "Text": "@allsegments", "Value": "@allsegments" });
                $.each(data, function () {
                    items.push({ "Text": this, "Value": this });
                });
                
                $("#SegmentId").kendoDropDownList({
                    dataTextField: "Text",
                    dataValueField: "Value",
                    dataSource: items
                });
            });
            
            
            $.getJSON('@Url.Action("GetRecommendations","Reporting")', { applicationId: appId }, function (data) {
                data:
                    var items = [];
                
                items.push({ "Text": "@allrecommendationboxes", "Value": "@allschemes" });
                $.each(data, function () {
                    items.push({ "Text": this, "Value": this });
                });

                $("#RecBoxId").kendoDropDownList({
                    dataTextField: "Text",
                    dataValueField: "Value",
                    dataSource: items
                });
            });
        }
        *@
    }

    $(function () {
        ApplicationChange();

        $("#AppID").change(function () {
            ApplicationChange();
        });
        
        if (nodeId == recommendedAssets) {
            $("#RecBox").css('display', 'block'); // Schemes
            //$("#Segments").css('display', 'block');
        }
        else if (nodeId == strategyComparison) {
            $("#RecBox").css('display', 'block'); // Schemes
            $("#StrategyStatus").css('display', 'block');
        }
        
        refreshReport();
    });
</script>
<style type="text/css">
#ReportingOptions {
    margin-left: 10px;
    margin-top: 10px;
}

#ReportingOptions .k-dropdown-wrap .k-state-default {
    font-size: .8em;
    width: 350px;
}
</style>
<div id="view-report" style="height:28px; white-space: nowrap;">
    <div id="ReportingOptions">
        <div style="float:left; margin-left:15px; margin-top:17px;"><span class="bold">From:</span></div>
        <div style="float:left; margin-left:5px; margin-top:10px;">
            @(Html.Kendo().DatePicker()
                    .Name("StartDate")
                    .Value(Model.StartDate)
                    .Max(DateTime.Today.AddDays(-1))
                    .Events(e => e.Change("startChange"))
                    .HtmlAttributes(new { style = "width:105px; height:1.75em;" })
                    )
        </div>
        <div style="float:left; margin-left:10px; margin-top:17px;"><span class="bold">To:</span></div>
        <div style="float:left; margin-left:5px; margin-top:10px;">
            @(Html.Kendo().DatePicker()
                  .Name("EndDate")
                  .Value(Model.EndDate)
                  .Min(Model.StartDate)
                  .Max(DateTime.Today.AddDays(-1))
                  .Events(e => e.Change("endChange"))
                  .HtmlAttributes(new { style = "width:105px; height:1.75em;" })
                  )
        </div>
        <div style="clear:both;"></div>

        @Html.Hidden("NodeID", Request.QueryString["NodeID"])<br/>

        <div style="float:left; margin-top: 8px;">
            @(Html.Kendo().DropDownList()
                  .BindTo(Model.ApplicationList)
                  .Name("AppID")
                  .Events(e => e.Change("ApplicationChange()"))
                  .HtmlAttributes(new { style = "width:225px;" })
                  .Value(Model.AppID)
                  )
        </div>
    
        @*
        <div id="Segments" style="float:left; margin-left:25px; margin-top:8px; display:none;">
            @(Html.Kendo().DropDownList()
                  .Name("SegmentId")
                  .DataTextField("Text")
                  .DataValueField("Value")
                  .BindTo(new List<SelectListItem>())
                  .HtmlAttributes(new { style = "width:200px;" })
                  )
        </div>
        
        <div id="RecBox" style="float:left; margin-left:25px; margin-top:8px; display:none;">
            @(Html.Kendo().DropDownList()
                  .Name("RecBoxId")
                  .DataTextField("Text")
                  .DataValueField("Value")
                  .BindTo(new List<SelectListItem>())
                  .HtmlAttributes(new { style = "width:250px;" })
                  )

        </div>
        *@

        <div id="StrategyStatus" style="float:left; margin-left:15px; margin-top:8px; display:none;">
            @(Html.Kendo().DropDownList()
                  .Name("Strategy")
                  .DataTextField("Text")
                  .DataValueField("Value")
                  .BindTo(new List<SelectListItem>() {
                      new SelectListItem() {
                          Text = @showallrecommendationstrategies,
                          Value = @showallrecommendationstrategies
                      },
                      new SelectListItem() {
                          Text = @showallactiverecommendationstrategies,
                          Value = @showallactiverecommendationstrategies
                      },
                      new SelectListItem() {
                          Text = @showallbutdeletedrecommendation,
                          Value = @showallbutdeletedrecommendation
                      }
                  })
                  .Value(@showallactiverecommendationstrategies)
                  .HtmlAttributes(new { style = "width:375px;" })
                  )
        </div>
        <div style="float:left; margin-left: 15px; margin-top:8px;"><button id="Submit" class="k-button btn-update">Submit</button></div>
    </div>
</div>
<div style="clear:both;"></div>
<div id="ViewReport" style="margin-left: 15px; margin-top:15px;"></div>

Resonance.Insight3.Web/Views/Reporting/ViewTrends.cshtml
@using System.ComponentModel
@using Resonance.Insight3.Web.Helpers
@model Resonance.Insight3.Web.ViewModels.Reporting.TrendsViewModel

<script type="text/javascript">
    var decimals = 0;
    function RefreshData() {
        var ID = "@Model.ID";
        var nodeType = '@Model.NodeType';

        var startDate = new Date($("#StartDate").val());
        var endDate = new Date($("#EndDate").val());
        
        var yesterday = new Date();
        yesterday.setDate(yesterday.getDate() - 1);

        if (endDate > yesterday) {
            ShowsysMessage("error", "The <i>To Date</i> must be no later than yesterday's date.");
            return (false);
        }

        if (startDate <= endDate) {
            var startYear = startDate.getFullYear();
            var startMonth = startDate.getMonth() + 1; // 0 based
            var startDay = startDate.getDate();
            
            var endYear = endDate.getFullYear();
            var endMonth = endDate.getMonth() + 1; // 0 based
            var endDay = endDate.getDate();
            
            $.ajax({
                url: "@Url.Action("GetTrendsData","Reporting")",
                cache: false,
                type: 'GET',
                data: { startYear: startYear, startMonth: startMonth, startDay: startDay, endYear: endYear, endMonth: endMonth, endDay: endDay, ID: ID, nodeType: nodeType },
                success: function (data) {
                    var dataSource = new kendo.data.DataSource({
                        data: data
                       , group: { field: "Group", dir: "asc" }
                       , sort: { field: "Category", dir: "asc" }
                    });
                    $("#@Model.ChartName").data("kendoChart").setDataSource(dataSource);
                }
            });
        } else {
            ShowsysMessage("error", "The From Date must be earlier than the To Date.");

            // Keep error message below in case User Experience wishes to use the modal dialog.
            // var errorMessage = "<br/><a href=\"#blank\" onclick=\"closeConfirmWindow()\">Close Window</a>";
            // displayErrorModal(errorMessage, 554, "Date Error");
        }
    }
    
    function startChange() {
        var endPicker = $("#EndDate").data("kendoDatePicker"),
            startDate = this.value();
        
        if (startDate) {
            startDate = new Date(startDate);
            startDate.setDate(startDate.getDate());
            endPicker.min(startDate);
        }
    }

    function endChange() {
        var startPicker = $("#StartDate").data("kendoDatePicker"),
            endDate = this.value();
        
        if (endDate) {
            endDate = new Date(endDate);
            endDate.setDate(endDate.getDate() - 1);
            startPicker.max(endDate);
        }
    }

    function onTrendsDataBound(e) {
        var chart = $("#@Model.ChartName").data("kendoChart");
        $.each(chart.options.series, function () {
            var obj = this;
            if (obj.color === "#0012F1" || obj.color === "#2D37B4" || obj.color === "#A62800" || obj.color === "#A62375") {
                obj.tooltip.color = "white";
            } else {
                obj.tooltip.color = obj.labels.color;
            }            
        });
    }
    
</script>
<div id="email-settings" style="height:28px; white-space: nowrap;">
    <div style="float:left; margin-top: 8px;">
        <span class="bold">Metric:</span>&#160;<span class="hotspot" data-hotspot="@this.InfoPanelResources("recommendationdemand")">@this.SharedResources("recommendationdemand")</span>
    </div>
    
    <div style="float:left; margin-left:25px; margin-top:8px;"><span class="bold">From:</span></div>
    <div style="float:left; margin-left:5px; margin-top:-1px;">
        @(Html.Kendo().DatePicker()
              .Name("StartDate")
              .Value(Model.StartDate)
              .Max(DateTime.Today.AddDays(-1))
              .Events(e => e.Change("startChange"))
              .HtmlAttributes(new { style = "width:105px; height:1.75em;" })
              )
    </div>
    <div style="float:left; margin-left:10px; margin-top:8px;"><span class="bold">To:</span></div>
    <div style="float:left; margin-left:5px; margin-top:-1px;">
        @(Html.Kendo().DatePicker()
              .Name("EndDate")
              .Value(Model.EndDate)
              .Min(Model.StartDate)
              .Max(DateTime.Today.AddDays(-1))
              .Events(e => e.Change("endChange"))
              .HtmlAttributes(new { style = "width:105px; height:1.75em;" })
              )
   </div>
    <div style="float:left; margin-left:5px; margin-top:-2px;"><button class="insight-submit-btn" onclick="RefreshData()">Update</button></div>
    <span style="float:left; margin-left:5px; margin-top:8px;" class="hotspot" data-hotspot="@this.InfoPanelResources("reportinglastupdated")">@Model.ReportingLastUpdated</span>
    <div style="clear:both;"></div>
</div>
<div style="clear:both;"></div>
<div id="trends_chart" class="chart-wrapper">
    @(Html.Kendo().Chart()
          .Name(@Model.ChartName)          
          .SeriesColors(@Model.SeriesColors)
          .Legend(legend => legend
                                .Position(ChartLegendPosition.Right)
          )          
          .ChartArea(chartArea => chartArea
                                      .Background("transparent")
          )
          .DataSource(ds => ds.Read(read => read.Action("GetTrendsModel", "Reporting", new { startYear=@Model.StartDate.Year, startMonth=@Model.StartDate.Month, startDay=@Model.StartDate.Day, 
                                                                                             endYear=@Model.EndDate.Year, endMonth=@Model.EndDate.Month, endDay=@Model.EndDate.Day, ID=Model.ID, nodeType=@Model.NodeType }))
                                .Group(group => group.Add("Group", typeof (string), ListSortDirection.Ascending))
                                .Sort(sort => sort.Add("Category").Ascending())
                                )
                                
                                
          .Series(series => series.Line(typeof (double), "Data").MissingValues(ChartLineMissingValues.Gap).GroupNameTemplate("#= group.value #"))
          .CategoryAxis(axis => { 
                                    axis.Axis.Member = "Category";
                                    axis.Labels(x => x.Rotation(-90));
                                })
          .ValueAxis(axis => axis.Numeric().Labels(labels => labels.Format("{0}%")))
          .Tooltip(tooltip => tooltip
                                  .Visible(true)
                                  .Template("#= series.name #: #= TooltipFormat(value) #"))
          .Events(events => events.DataBound("onTrendsDataBound"))
          )
</div>

<script type="text/javascript">
    $(window).resize(function(){
        if ($("#@Model.ChartName").length>0) {
            $("#@Model.ChartName").data("kendoChart").redraw();
        }
    });
    
    function TooltipFormat(value) {
        var dec = value.toString().substring(value.toString().indexOf('.') + 1);
        var places = 0;
        for (var i = 0; i < dec.length; i++) {
            if (dec[i] != 0) {
                places = i + 2;
                break;
            }
        }
        return value.toFixed(places) + '%';
    }    
</script>