Resonance.Insight3.Web/ViewModels/Catalog/HeaderViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Resonance.Insight3.Web.ViewModels.Catalog
{
    public class HeaderViewModel
    {
        public string CatalogName { get; set; }
    }
}

Resonance.Insight3.Web/ViewModels/Experience/ExperienceBiases.cs
using System;

namespace Resonance.Insight3.Web.ViewModels.Experience
{
    public class ExperienceBiases
    {
        private double? _weight;

        public int BiasID { get; set; }
        public double? Weight
        {
            get
            {
                if (_weight.HasValue)
                {
                    return _weight;
                }

                return 0;
            }

            set { _weight = value; }
        }

        public string ListName { get; set; }
    }
}

Resonance.Insight3.Web/ViewModels/Experience/ExperienceBoosts.cs
using System.Collections.Generic;

namespace Resonance.Insight3.Web.ViewModels.Experience
{
    public class ExperienceBoosts
    {
        public int ExperienceID { get; set; }
        public List<ExperienceBiases> ExperienceBiases { get; set; }
        public ExperienceDetails ExperienceDetails { get; set; }
        public List<Model> ExperienceModels { get; set; }
    }
}

Resonance.Insight3.Web/ViewModels/Experience/ExperienceDetails.cs
using System;

namespace Resonance.Insight3.Web.ViewModels.Experience
{
    public class ExperienceDetails
    {
        private int _pool;

        public int Pool { get; set; }
        
        public int PoolMultipliedByTen
        {
            get
            {
                if (Pool >= 10)
                {
                    _pool = 10;
                }
                else if (Pool == 0)
                {
                    _pool = 0;
                }
                else
                {
                    _pool = Pool*10;
                }

                return _pool;
            }

            set { _pool = value;  }
        }

        public int Profile { get; set; }
    }
}

Resonance.Insight3.Web/ViewModels/Experience/ExperienceModels.cs
using System;

namespace Resonance.Insight3.Web.ViewModels.Experience
{
    public class Model
    {
        private double? _weight;

        public string CatalogID { get; set; }
        public string Description { get; set; }
        public int ModelID { get; set; }
        public string Name { get; set; }
        public double? Weight
        {
            get
            {
                if (_weight.HasValue)
                {
                    return _weight;
                }

                return 0;
            }

            set { _weight = value; }
        }
    }
}

Resonance.Insight3.Web/ViewModels/Experience/ExperienceNodeViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web;
using System.Web.Mvc;
using Resonance.Insight3.Web.ViewModels.Variant;

namespace Resonance.Insight3.Web.ViewModels.Experience
{
    public class ExperienceNodeViewModel
    {
        public int SchemeID { get; set; }
        public int ExperienceID { get; set; }
        public int? CreatedVariantId { get; set; } // newly created Strategy(Variant) id (via CreateStrategies dialog)
        
        [Required()]
        [StringLength(50, ErrorMessage = "Must be less than 50 characters")]
        [Display(Name = "Name")]
        public string Name { get; set; }

        [StringLength(255, ErrorMessage = "Must be less than 255 characters")]
        public string Description { get; set; }

        public string Status { get; set; }
        public decimal? Traffic { get; set; }
        public int StrategyCount { get; set; }

        // Added to allow for local data binding
        public List<int> StrategyIDList { get; set; }
        public List<VariantRule> VariantRules { get; set; }
        public List<ExperienceStrategyDecisionPlan> DecisionPlans { get; set; }
        public List<SelectListItem> Priority { get; set; }
        public List<SelectListItem> NumberOfAssets { get; set; }

        public bool ShowRules
        {
            get
            {
                if (HttpContext.Current.Session["Strategies.ShowRules"] == null)
                {
                    HttpContext.Current.Session["Strategies.ShowRules"] = true;
                }
                return (bool)HttpContext.Current.Session["Strategies.ShowRules"];
            }
            set
            {
                HttpContext.Current.Session["Strategies.ShowRules"] = value;
            }
        }

        public bool ShowDecisionPlan
        {
            get
            {
                if (HttpContext.Current.Session["Strategies.ShowDecisionPlan"] == null)
                {
                    HttpContext.Current.Session["Strategies.ShowDecisionPlan"] = true;
                }
                return (bool)HttpContext.Current.Session["Strategies.ShowDecisionPlan"];
            }
            set
            {
                HttpContext.Current.Session["Strategies.ShowDecisionPlan"] = value;
            }
        }
    }
}

Resonance.Insight3.Web/ViewModels/Experience/ExperienceStrategy.cs
namespace Resonance.Insight3.Web.ViewModels.Experience
{
    public class ExperienceStrategy
    {
        public int StrategyID { get; set; }
        public string Name { get; set; }
        public double? Impressions { get; set; }
        public string Catalog { get; set; }
        public string CatalogImage { get; set; }
        public string PersonalizationType { get; set; }
        public string Status { get; set; }
        public int? Priority { get; set; }
        public string Rules { get; set; }
        public int? NumberOfItems { get; set; }
        public int? MinItemsReturned { get; set; }
        public bool? BreakOnMinItemsReturned { get; set; }
    }
}

Resonance.Insight3.Web/ViewModels/Experience/ExperienceStrategyDecisionPlan.cs
namespace Resonance.Insight3.Web.ViewModels.Experience
{
    public class ExperienceStrategyDecisionPlan
    {
        public int StrategyID { get; set; }
        public int? NumberOfItems { get; set; }
        public int? MinItems { get; set; }
        public bool? BreakOnMinItems { get; set; }
        public string SlotInfo { get; set; }
    }
}

Resonance.Insight3.Web/ViewModels/Experience/ExperienceViewModel.cs
using System.Collections.Generic;

namespace Resonance.Insight3.Web.ViewModels.Experience
{
    public class ExperienceViewModel
    {
        public List<ExperienceBiases> ExperienceBiases { get; set; }
        public ExperienceDetails ExperienceDetails { get; set; }
        public List<Model> ExperienceModel { get; set; }
    }
}

Resonance.Insight3.Web/Controllers/ExperienceController.cs
using System;
using System.Linq;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Web.UI;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Resonance.Insight3.Web.CertonaService;
using Resonance.Insight3.Web.Models;
using Resonance.Insight3.Web.ViewModels.Experience;
using Resonance.Insight3.Web.ViewModels.Scheme;
using Resonance.Insight3.Web.ViewModels.Variant;
using VariantModel = Resonance.Insight3.Web.Models.VariantModel;

namespace Resonance.Insight3.Web.Controllers
{
    public class ExperienceController : Controller
    {
        public PartialViewResult Header(int id)
        {
            var model = ExperienceModel.GetExperienceDetails(id);
            return PartialView(model);
        }

        public PartialViewResult ViewModifiers(int id)
        {
            var model = ExperienceModel.GetExperienceBoosts(id);
            return PartialView(model);
        }

        [HttpPost]
        public JsonResult UpdateExperienceModifiers(int experienceId, int pool, int profile)
        {
            var model = ExperienceModel.UpdateExperienceModifiers(experienceId, pool, profile);
            return Json(model);
        }

        [HttpGet]
        [OutputCache(Location = OutputCacheLocation.None, NoStore = true)] 
        public PartialViewResult ManageModifiers(int id, int cpsId)
        {
            var model = ExperienceModel.GetExperienceBoosts(id);
            ViewBag.cpsId = cpsId;
            return PartialView(model);
        }

        public PartialViewResult ViewDecisionPlan()
        {
            return PartialView();
        }

        public PartialViewResult ViewDetails(int id)
        {
            var model = ExperienceModel.GetExperienceDetails(id);
            return PartialView(model);
        }

        [HttpGet]
        [OutputCache(Location = OutputCacheLocation.None, NoStore = true)]
        public PartialViewResult ManageDetails(int id, int cpsId)
        {
            var model = ExperienceModel.GetExperienceDetails(id);
            ViewBag.cpsId = cpsId;
            return PartialView(model);
        }

        [HttpPost]
        public void ManageDetails(ExperienceNodeViewModel details)
        {
            ExperienceModel.UpdateExperienceDetails(details);
        }

        [HttpGet]
        [OutputCache(Location = OutputCacheLocation.None, NoStore=true)]
        public PartialViewResult CreateStrategies(int NodeId, string updateTargetId)
        {
            var vm = new VariantNodeViewModel() { ExperienceID = NodeId };

            ViewBag.UpdateTargetId = updateTargetId;
            return PartialView(vm);
        }

        [HttpPost]
        public PartialViewResult CreateNewStrategy(VariantNodeViewModel variant)
        {
            int newId = VariantModel.CreateVariant(variant);

            var vm = ExperienceModel.GetExperienceDetailsWithRules(variant.ExperienceID);
            vm.CreatedVariantId = newId;
            return PartialView("ViewStrategies", vm);
        }

        public PartialViewResult ViewStrategies(int id)
        {
            var model = ExperienceModel.GetExperienceDetailsWithRules(id);
            return PartialView(model);
        }

        public PartialViewResult ManageStrategies(int id, int cpsId)
        {
            var model = ExperienceModel.GetExperienceDetailsWithRules(id);
            ViewBag.cpsId = cpsId;
            return PartialView(model);
        }

        public PartialViewResult ViewTrends(int id)
        {
            var model = ReportingModel.GetTrendsExperienceData(id);
            return PartialView("~/Views/Reporting/ViewTrends.cshtml", model);
        }

        
        public ActionResult HierarchyBinding_Experiences(int experienceID, [DataSourceRequest] DataSourceRequest request)
        {
            List<ExperienceStrategy> strategies = ExperienceModel.GetExperienceStrategies(experienceID);
            return Json(strategies.ToDataSourceResult(request));
        }
        
        public ActionResult HierarchyBinding_Strategies(int experienceID, int strategyID, [DataSourceRequest] DataSourceRequest request)
        {
            // get the rules based on strategy/variant ID
            var rules = Models.VariantModel.GetVariantRulesForDetailGrid(strategyID);            
            return Json(rules.ToDataSourceResult(request));
        }
        
        //[HttpGet]
        //public JsonResult GetDecisionContent(int experienceID, int strategyID)
        //{
        //    var exp = ExperienceModel.GetExperienceStrategies(experienceID).FirstOrDefault(x => x.StrategyID == strategyID);
        //    var str = VariantModel.GetVariantSlotString(strategyID);

        //    string s1 =
        //        String.Format(
        //            "<div style='float: left; width: 25%;background-color:PaleTurquoise'>No. of Assets Requested: {0}</div>",
        //            exp != null
        //                ? (exp.NumberOfItems.HasValue ? exp.NumberOfItems.Value.ToString() : string.Empty)
        //                : string.Empty);
        //    string s2 = String.Format("<div style='float: left; width: 25%;background-color:PaleTurquoise'>Min. Required:{0}</div>",
        //            exp != null
        //                ? (exp.MinItemsReturned.HasValue ? exp.MinItemsReturned.Value.ToString() : string.Empty)
        //                : string.Empty);
        //    string s3 = String.Format("<div style='float: left; width: 25%;background-color:PaleTurquoise'>Break on Min: {0}</div>",
        //            exp != null
        //                ? (exp.BreakOnMinItemsReturned.HasValue ? (exp.BreakOnMinItemsReturned.Value == true ? "Yes" : "No"): string.Empty)
        //                : String.Empty);            

        //    string s4 = String.Format("<div style='float: left; width: 25%;background-color:PaleTurquoise'>Slots: {0}</div>", str);
            
        //    return Json(String.Format("{0} {1} {2} {3}",s1,s2,s3,s4), JsonRequestBehavior.AllowGet);
        //}

        [HttpGet]
        public PartialViewResult GetDecisionContent(int experienceID, int strategyID)
        {
            var exp = ExperienceModel.GetExperienceStrategies(experienceID).FirstOrDefault(x => x.StrategyID == strategyID);
            var str = Models.VariantModel.GetVariantSlotString(strategyID);

            var model = new ExperienceStrategyDecisionPlan()
                            {
                                NumberOfItems = (exp != null ? exp.NumberOfItems : null),
                                MinItems = (exp != null ? exp.MinItemsReturned : null),
                                BreakOnMinItems = (exp != null ? exp.BreakOnMinItemsReturned : null),
                                SlotInfo = str
                            };

            return PartialView("DecisionPlanFooter",model);
        }

        [HttpPost]
        public JsonResult SetRulesDisplayState(bool showRules)
        {
            var model = new ExperienceNodeViewModel();
            model.ShowRules = showRules;

            return Json("Success");
        }

        [HttpPost]
        public JsonResult SetDecisionPlanDisplayState(bool showDecisionPlan)
        {
            var model = new ExperienceNodeViewModel();
            model.ShowDecisionPlan = showDecisionPlan;

            return Json("Success");
        }

        [AcceptVerbs(HttpVerbs.Post)]        
        public ActionResult ExperienceInline_Update([DataSourceRequest] DataSourceRequest request, SchemeExperience experience)
        {
            ExperienceModel.UpdateExperienceDetails(experience);
           
            // var vm = SchemeModel.GetSchemeExperiences(experience.SchemeID);
            //return Json(vm.Experiences);
           
            return Json(ModelState.ToDataSourceResult());
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult GetExperiences([DataSourceRequest]DataSourceRequest request, int containerID)
        {
            var vm = SchemeModel.GetSchemeExperiences(containerID);
            DataSourceResult result = vm.Experiences.ToDataSourceResult(request);
            return Json(result);
        }

        public MvcHtmlString GetPersonalizationTypeDdl(string catalogID)
        {
            var list = VariantModel.GetRecTypeList(catalogID);
            var ddl = "<select name='MethodID' id='MethodID' style='width: 200px;' data-original-value=''>";
            if (list.Count == 0)
            {
                ddl += "<option value=''>No Personalization Types</option>";
            }
            else
            {
                foreach (var recType in list)
                {
                    ddl += string.Format("<option value='{0}'>{1}</option>", recType.MethodID.ToString(), recType.Name);
                }
            }
            
            ddl += "</select>";

            return MvcHtmlString.Create(ddl);
        }
    }

}

Resonance.Insight3.Web/Views/Experience/CreateStrategies.cshtml
@using System.Collections
@using Resonance.Insight3.Web.Helpers
@using Resonance.Insight3.Web.HtmlHelpers
@model Resonance.Insight3.Web.ViewModels.Variant.VariantNodeViewModel
@{ 
    const string formName = "frmCreateStrategies";
    const string createContainer = "#insight-create-dialog";
    string updateTargetId = ViewBag.UpdateTargetId;
}

@using (Ajax.BeginForm("CreateNewStrategy", "Experience",
    new AjaxOptions { HttpMethod = "Post", UpdateTargetId = @updateTargetId, OnSuccess = "onAjaxPostSuccess", OnFailure = "onAjaxPostFailure" }, new { id = @formName }))
{
    @Html.HiddenFor(m => m.ExperienceID, Model.ExperienceID)

    <div style="float: left;">
        <span class="bold">@Html.RequiredAsterik(this) @this.SharedResources("name")</span><br/>
        @Html.TextBoxForWithDefault(m => m.Name, string.Empty, 200)<br/>
        @Html.ValidationMessageFor(m => m.Name)<br/><br/>
    
        @this.SharedResources("description")<br/>
        @Html.TextAreaForWithDefault(m => m.Description, string.Empty, 4, 25)<br/>
        @Html.ValidationMessageFor(m => m.Description)<br/><br/>
        
        @this.SharedResources("containertitle")<br/>
        @Html.TextBoxForWithDefault(m => m.ContainerTitle, string.Empty, 200)<br/>
        @Html.ValidationMessageFor(m => m.ContainerTitle)<br/><br/>
    </div>
    
    <div style="float: left; padding: 0.4em;">
        @this.SharedResources("catalog")<br/>
        @Html.DropDownListForWithDefault(m => m.CatalogID, @Model.ApplicationCatalogList, string.Empty, 200)<br/>
        @Html.ValidationMessageFor(m => m.CatalogID)<br/><br/>

        @this.SharedResources("personalizationtype")<br/>
        <div id="personalization-type-list"></div><br/>
    </div>
    
    <div style="float: left; padding: 0.4em;">
        @this.SharedResources("priority")<br/>
        @Html.DropDownListForWithDefault(m => m.Priority,@Model.PriorityList, string.Empty, 100)<br/><br/>
        
        @this.SharedResources("nbrofassets")<br/>
        @Html.DropDownListForWithDefault(m => m.NumberOfAssets, @Model.NumberOfAssetsList, string.Empty, 100)<br/>
    </div>
    
    <div style="clear: both; text-align: right;">
        <input type="submit" class="insight-submit-btn" value="Save" id="btnCreateStrategy" disabled="disabled" />&#160;
        <button onclick="cancelJqueryDialog('Strategies', '@createContainer')" class="insight-cancel-btn" type="button" value="Cancel">Cancel</button>
    </div>
}
<script type="text/javascript">
    function onAjaxPostSuccess(response) { 
        ShowsysMessage('success', 'Strategy added successful');
        cancelJqueryDialogContinue('@createContainer');
    }

    function onAjaxPostFailure(response) {
        ShowsysMessage('error', 'An error occured during the save process');
    }
    
    var cp = contentPanels.GetCurrentContentPanel();
    var cps = cp.GetContentPanelSection("Strategies");
    cps.SetDirtyContainer('@formName');

    $('#@formName :input').change(function () { toggleSaveButton('@formName'); });
    $('#@formName :input').on('keypress', function () { toggleSaveButton('@formName'); });

    $('#CatalogID').change(function() {
        var catalogID = $(this).val();
        var personalizationTypeListUrl = '@Url.Action("GetPersonalizationTypeDdl", "Experience")';
        if (catalogID != '') {
            $.get(personalizationTypeListUrl, { catalogID: catalogID }, function (response) {
                $('#personalization-type-list').html(response);
            });
        } else {
            $('#personalization-type-list').html('');
        }
    });
</script>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")"></script>

Resonance.Insight3.Web/Views/Experience/DecisionPlanFooter.cshtml
@using Resonance.Insight3.Web.Helpers
@model Resonance.Insight3.Web.ViewModels.Experience.ExperienceStrategyDecisionPlan

<div style='float: left; width: 25%;background-color:PaleTurquoise'><span class="hotspot" data-hotspot="@this.InfoPanelResources("numberOfAssets")"><span class="bold">No. of Assets Requested:</span></span>&#160;@Model.NumberOfItems</div>
<div style='float: left; width: 25%;background-color:PaleTurquoise'><span class="hotspot" data-hotspot="@this.InfoPanelResources("minRequired")"><span class="bold">Min. Required:</span></span>&#160;@Model.MinItems</div>
<div style='float: left; width: 25%;background-color:PaleTurquoise'><span class="hotspot" data-hotspot="@this.InfoPanelResources("breakOnMin")"><span class="bold">Break on Min:</span></span>&#160;@Model.BreakOnMinItems</div>
<div style='float: left; width: 25%;background-color:PaleTurquoise'><span class="hotspot" data-hotspot="@this.InfoPanelResources("slots")"><span class="bold">Slots:</span></span>&#160;@Model.SlotInfo</div>

Resonance.Insight3.Web/Views/Experience/Header.cshtml
@model Resonance.Insight3.Web.ViewModels.Experience.ExperienceNodeViewModel

<div style="border-bottom: solid 1px #000; padding: 6px 5px 2px 5px;">
    <span style="font-size: 130%;">@Model.Name</span> - Experience
</div>

Resonance.Insight3.Web/Views/Experience/ManageDetails.cshtml
@using Resonance.Insight3.Web.Helpers
@using Resonance.Insight3.Web.HtmlHelpers
@model Resonance.Insight3.Web.ViewModels.Experience.ExperienceNodeViewModel
@{
    string cpsId = Convert.ToString(ViewBag.cpsId);
    var formName = string.Concat("frmManageDetails", cpsId);
}
@using (Ajax.BeginForm("ManageDetails", "Experience",
        new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "", OnSuccess = "onAjaxPostSuccess", OnFailure = "onAjaxPostFailure" }, new { id = @formName }))
{
    <div style="display: block; width: 100%; overflow: auto">
        @Html.Hidden("cps-editmode-flag", "1", new { id = "cps-editmode-flag", data_cps_id = cpsId})
        @Html.Hidden("cpsId", @cpsId, new { id = "cpsId" })
        @Html.HiddenFor(m => m.ExperienceID)
        <div style="float: left; width: 25%;">
            <span class="bold">@Html.RequiredAsterik(this) @this.SharedResources("experience")</span>
            <br/>
            @Html.TextBoxForWithDefault(m => m.Name, Model.Name, 250)<br/>
            @Html.ValidationMessageFor(m => m.Name)
        </div>
        <div style="float: left; width: 25%;">
            <span class="bold">@this.SharedResources("description")</span>
            <br/>
            @Html.TextAreaForWithDefault(m => m.Description, Model.Description, 5, 35)<br/>
            @Html.ValidationMessageFor(m => m.Description)
        </div>
        <div style="float: left; width: 25%;">
            <span class="hotspot" data-hotspot="@this.InfoPanelResources("traffic")"><span class="bold">@this.SharedResources("traffic")</span></span><br/>
            @Model.Traffic%
        </div>
        <div style="float: left; width: 25%;">
            <span class="hotspot" data-hotspot="@this.InfoPanelResources("status")"><span class="bold">@this.SharedResources("status")</span></span>
            <br/>
            @Model.Status
        </div>
        <br/>

        <div style="clear: both; text-align: right;">
            <input type="submit" class="insight-submit-btn" value="Save" id="btnSaveExperienceDetails" disabled="disabled" />&#160;
            <button onclick="cancelEditCPS('@cpsId')" class="insight-cancel-btn" type="button" value="Cancel">Cancel</button>
        </div>
    </div>
}
<script type="text/javascript">
    function onAjaxPostSuccess(response) {
        ShowsysMessage('success', 'Experience saved successfully');

        var cp = contentPanels.GetCurrentContentPanel();
        cps = cp.GetContentPanelSectionById('@cpsId');
        if (cps) {
            cps.IsEditing(false);
        }
        cancelEditCPS('@cpsId');
    }
    function onAjaxPostFailure(response) {
        ShowsysMessage('error', 'An error occured during the save process');
    }
    $('#@formName :input').change(function () { toggleSaveButton('@formName'); });
    $('#@formName :input').on('keypress', function () { toggleSaveButton('@formName'); });
   
</script>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")"></script>

Resonance.Insight3.Web/Views/Experience/ManageModifiers.cshtml
@using Resonance.Insight3.Web.Helpers
@model Resonance.Insight3.Web.ViewModels.Experience.ExperienceBoosts
@{
    string cpsId = Convert.ToString(ViewBag.cpsId);
}
<script type="text/javascript" src="~/Scripts/jquery.knob.js"></script>
<script type="text/javascript">
    $(function () {
        $(".dial").dial({
            /* Place holder options
            change: function (value) {},
            release: function (value) {},
            cancel: function () {}
            */
        });

        // A lower process overrides any inline-css attribute on the input tag which is why jQuery is used to execute these stylings
        $(".dial").css('margin-top', '-60px').css('margin-left', '12px').css('border', '1px solid #FFC30B');

        $("#btnSaveModifiers").click(function () {
            $.ajax({
                url: '@Url.Action("UpdateExperienceModifiers", "Experience")',
                type: 'POST',
                data: { experienceId: $("#ExperienceID").val(), pool: $("#Pool").val(), profile: $("#Profile").val() },
                success: function (data) {
                    if (data == true) {
                        ShowsysMessage('success', 'Experience Modifiers Updated Successfully');

                        var cp = contentPanels.GetCurrentContentPanel();
                        cps = cp.GetContentPanelSectionById('@cpsId');
                        if (cps) {
                            cps.IsEditing(false);
                        }
                        cancelEditCPS('@cpsId');
                    } else {
                        ShowsysMessage('error', 'An error occured during the save process');
                    }
                },
                error: function (xhr, status, error) {
                    alert('an error occurred!\n\nstatus: ' + status + '\nerror: ' + error.name + '\nerror message: ' + error.message);
                }
            });
        });
    });

</script>
@Html.HiddenFor(m => m.ExperienceID)
@Html.Hidden("cpsId", @cpsId, new { id = "cpsId" })
@Html.Hidden("cps-editmode-flag", "1", new { id = "cps-editmode-flag", data_cps_id = cpsId})
<div class="modifiers-container">
    <div class="modifiers-header-bg" style="border-left-style: solid;"><span class="hotspot" data-hotspot="@this.InfoPanelResources("pool")">Pool</span></div>
    <div>
        <div class="modifiers-dial-wrapper">
            <input id="Pool" class="dial" data-width="60" data-thickness=".3" data-fgColor="#87CEEB" data-bgColor="#C0C0C0" data-angleOffset="0" data-readOnly="false" data-min="0" data-max="10" data-original-value="@Model.ExperienceDetails.Pool" value="@Model.ExperienceDetails.Pool" />
        </div>
        <div class="modifiers-dial-notation">x</div>
    </div>
</div>
<div class="modifiers-container" style="border-left-style:none;">
    <div class="modifiers-header-bg"><span class="hotspot" data-hotspot="@this.InfoPanelResources("profile")">Profile</span></div>
    <div>
        <div class="modifiers-dial-wrapper">
            <input id="Profile" class="dial" data-id="Profile" data-width="60" data-thickness=".3" data-fgColor="#87CEEB" data-bgColor="#C0C0C0" data-angleOffset="0" data-readOnly="false" data-min="0" data-max="100" data-original-value="@Model.ExperienceDetails.Profile" value="@Model.ExperienceDetails.Profile" />
        </div>
        <div class="modifiers-dial-notation">%</div>
    </div>
</div>

<div style="clear: both; text-align: right;">
    <input type="submit" class="insight-submit-btn" value="Save" id="btnSaveModifiers" />&#160;
    <button onclick="cancelEditCPS('@cpsId')" class="insight-cancel-btn" type="button" value="Cancel">Cancel</button>
</div>

Resonance.Insight3.Web/Views/Experience/ViewDetails.cshtml
@using Resonance.Insight3.Web.Helpers
@model Resonance.Insight3.Web.ViewModels.Experience.ExperienceNodeViewModel

<div style="display: block; width: 100%;">
    @Html.Hidden("cps-editmode-flag", "0", new { id = "cps-editmode-flag" })
    <div style="float: left; width: 25%;">
        <span class="bold">@this.SharedResources("experience")</span>
        <br/>
        @Model.Name
    </div>
    <div style="float: left; width: 25%;">
        <span class="bold">@this.SharedResources("description")</span>
        <br/>
        @Model.Description
    </div>
    <div style="float: left; width: 25%;">
        <span class="hotspot" data-hotspot="@this.InfoPanelResources("traffic")"><span class="bold">@this.SharedResources("traffic")</span></span>
        <br/>
        @Model.Traffic%
    </div>
    <div style="float: left; width: 25%;">
        <span class="hotspot" data-hotspot="@this.InfoPanelResources("status")"><span class="bold">@this.SharedResources("status")</span></span>
        <br/>
        @Model.Status
    </div>    
    <div style="clear: both;"></div>
</div>