Resonance.Insight3.Web/ViewModels/Catalog/HeaderViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Resonance.Insight3.Web.ViewModels.Catalog
{
    public class HeaderViewModel
    {
        public string CatalogName { get; set; }
    }
}

Resonance.Insight3.Web/ViewModels/Variant/Details.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web.Mvc;
using Resonance.Insight3.Web.Models;

namespace Resonance.Insight3.Web.ViewModels.Variant
{
    public class VariantDetails
    {
        private int _poolFactor ;

        public int VariantId { get; set; }
        public string Catalog { get; set; }
        public string CatalogId { get; set; }
        
        [StringLength(255, ErrorMessage = "Must be less than 255 characters")]
        public string ContainerTitle { get; set; }
        
        [StringLength(255, ErrorMessage = "Must be less than 255 characters")]
        public string Description { get; set; }
        
        public string Icon_FileName { get; set; }
        
        [StringLength(100, ErrorMessage = "Must be less than 100 characters")]
        public string Name { get; set; }
        
        public int NumberOfAssets { get; set; }
        public string PersonalizationType { get; set; }
        public int MethodId { get; set; }
        public int PoolFactor { get; set; }
        public int PoolFactorMultipliedByTen
        {
            get
            {
                if (PoolFactor >= 10)
                {
                    _poolFactor = 10;
                }
                else if (PoolFactor == 0)
                {
                    _poolFactor = 0;
                }
                else
                {
                    _poolFactor = PoolFactor*10;
                }

                return _poolFactor;
            }
        }
        public int Priority { get; set; }
        public string RecommendationType { get; set; }
        public int SubjectWeight { get; set; }
        public string  Status { get; set; }

        public List<SelectListItem> PersonalizationTypeList 
        {
            get
            {
                if (!string.IsNullOrEmpty(CatalogId))
                {
                    var list = Resonance.Insight3.Web.Models.VariantModel.GetRecTypeList(CatalogId);
                    return list.Select(s => new SelectListItem { Text = s.Name, Value = s.MethodID.ToString(), Selected = (s.Name == PersonalizationType) ? true : false }).ToList();         
                }
                return new List<SelectListItem>();
            }
        }

        public List<SelectListItem> StatusList 
        {
            get
            {
                var list = ApplicationModel.GetStatusList();
                return list.Select(s => new SelectListItem {Text = s, Value = s}).ToList();                
            }
        }
    }
}

Resonance.Insight3.Web/ViewModels/Variant/DetailsViewModel.cs
namespace Resonance.Insight3.Web.ViewModels.Variant
{
    public class DetailsViewModel
    {
        public VariantDetails VariantDetails { get; set; }
    }
}

Resonance.Insight3.Web/ViewModels/Variant/ExperienceDetails.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Resonance.Insight.Web.Bytes.ViewModels.Variant
{
    public class ExperienceDetails
    {
        public int Pool { get; set; }
        public double Profile { get; set; }
    }
}

Resonance.Insight3.Web/ViewModels/Variant/Rule.cs
namespace Resonance.Insight3.Web.ViewModels.Variant
{
    public class Rule
    {
        public int StrategyID { get; set; }
        public string Name { get; set; }
        public string Conditions { get; set; }
    }
}

Resonance.Insight3.Web/ViewModels/Variant/VariantBiases.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Resonance.Insight3.Web.ViewModels.Variant
{
    public class VariantBiases
    {
        private double? _weight;

        public int BiasID { get; set; }
        public double? Weight {
            get
            {
                if (_weight.HasValue)
                {

                    return _weight * 100;
                }

                return 0;
            }

            set { _weight = value; }
        }

        public string ListName { get; set; }
    }
}

Resonance.Insight3.Web/ViewModels/Variant/VariantBoosts.cs
using System.Collections.Generic;

namespace Resonance.Insight3.Web.ViewModels.Variant
{
    public class VariantBoosts
    {
        public int VariantID { get; set; }
        public List<VariantBiases> VariantBiases { get; set; }
        public VariantDetails VariantDetails { get; set; }
        public List<VariantModel> VariantModels { get; set; }
    }
}

Resonance.Insight3.Web/ViewModels/Variant/VariantModels.cs
using System;

namespace Resonance.Insight3.Web.ViewModels.Variant
{
    public class VariantModel
    {
        private double? _weight;

        public string CatalogID;
        public string Description;
        public int ModelID;
        public string Name;
        public double? Weight
        {
            get
            {
                if (_weight.HasValue) 
                {
                    return _weight;
                }

                return 0;
            }

            set { _weight = value; }
        }
    }
}

Resonance.Insight3.Web/ViewModels/Variant/VariantNodeViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.ServiceModel;
using System.Web.Mvc;
using Resonance.Insight3.Web.CertonaService;
using Resonance.Insight3.Web.FormAuthentication;
using Resonance.Insight3.Web.Models;

namespace Resonance.Insight3.Web.ViewModels.Variant
{
    public class VariantNodeViewModel : ModelBase
    {
        public int ExperienceID { get; set; }
        public int VariantID { get; set; }
        
        [Required(ErrorMessage="Please select a Catalog")]
        public String CatalogID { get; set; }
        
        public Int32 Priority { get; set; }
        public Int32 NumberOfAssets { get; set; }
        public Int32 MethodID { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "Must be less than 100 characters")]
        [Display(Name = "Name")]
        public string Name { get; set; }

        [StringLength(255, ErrorMessage = "Must be less than 255 characters")]
        public string Description { get; set; }

        [StringLength(255, ErrorMessage = "Must be less than 255 characters")]
        public string ContainerTitle { get; set; }

#region "Drop Down Lists"

        public List<SelectListItem> PriorityList
        {
            get
            {
                var _lastPriority = 0;
                using (_certonaService = new CertonaServiceClient())
                {
                    try
                    {
                        UserDTO user = FormsAuthenticationWrapper.User;
                        var request = new GetLastVariantPriorityByExperienceRequest()
                        {
                            User = user,
                            ExperienceID = this.ExperienceID
                        };
                        var response = _certonaService.GetLastVariantPriorityByExperience(request);

                        _lastPriority = response.LastPriority;
                    }
                    catch (TimeoutException exception)
                    {
                        _certonaService.Abort();
                        throw;
                    }
                    catch (CommunicationException exception)
                    {
                        _certonaService.Abort();
                        throw;
                    }
                }

                var priorityList = new List<SelectListItem>();
                for (var i = 1; i <= (_lastPriority + 1); i++)
                {
                    priorityList.Add(new SelectListItem() { Text = i.ToString(), Value = i.ToString() });
                }
                return priorityList;
            }
        }

        public List<SelectListItem> ApplicationCatalogList
        {
            get
            {
                using (_certonaService = new CertonaServiceClient())
                {
                    try
                    {
                        UserDTO user = FormsAuthenticationWrapper.User;
                        var request = new GetApplicationCatalogsByExperienceRequest()
                            {
                                User = user,
                                ExperienceID = this.ExperienceID
                            };
                        var response = _certonaService.GetApplicationCatalogsByExperience(request);
                        var applicationCatalogList = new List<SelectListItem>();
                        applicationCatalogList.Add(new SelectListItem() { Selected = true, Text = "Select a Catalog", Value = "" });
                        applicationCatalogList.AddRange(response.Catalogs.Select(catalogId => new SelectListItem() { Text = catalogId.CatalogName, Value = catalogId.CatalogID }).ToList());
                        return applicationCatalogList;
                    }
                    catch (TimeoutException exception)
                    {
                        _certonaService.Abort();
                        throw;
                    }
                    catch (CommunicationException exception)
                    {
                        _certonaService.Abort();
                        throw;
                    }
                }
            }
        }

        public List<SelectListItem> NumberOfAssetsList
        {
            get
            {
                using (_certonaService = new CertonaServiceClient())
                {
                    try
                    {
                        UserDTO user = FormsAuthenticationWrapper.User;
                        var appDetailRequest = new GetSchemeNumberOfItemsByExperienceRequest { User = user, ExperienceID = this.ExperienceID };
                        var appDetailResponse = _certonaService.GetSchemeNumberOfItemsByExperience(appDetailRequest);
                        var numberOfItems = appDetailResponse.NumberOfItems;

                        var numberOfAssetsList = new List<SelectListItem>();
                        for (var i = 1; i <= numberOfItems; i++)
                        {
                            numberOfAssetsList.Add(new SelectListItem() { Text = i.ToString(), Value = i.ToString() });
                        }
                        return numberOfAssetsList;
                    }
                    catch (TimeoutException exception)
                    {
                        _certonaService.Abort();
                        throw;
                    }
                    catch (CommunicationException exception)
                    {
                        _certonaService.Abort();
                        throw;
                    }
                }
            }
        }
#endregion
    }
}

Resonance.Insight3.Web/Controllers/VariantController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using System.Web.UI;
using Resonance.Insight3.Web.Models;
using Resonance.Insight3.Web.ViewModels.Variant;
using Resonance.Insight3.Web.ViewModels.Rule;
using VariantModel = Resonance.Insight3.Web.Models.VariantModel;

namespace Resonance.Insight3.Web.Controllers
{
    public class VariantController : Controller
    {
        public PartialViewResult ViewModifiers(int id)
        {
            var model = VariantModel.GetVariantBoosts(id);
            return PartialView(model);
        }

        [HttpPost]
        public JsonResult UpdateVariantModifiers(string variantId, int pool, int profile, List<VariantBiases> biases, List<ViewModels.Variant.VariantModel> variants)
        {
            var model = VariantModel.UpdateVariantModifiers(variantId, pool, profile, biases, variants);
            return Json(model);
        }

        [HttpGet]
        [OutputCache(Location = OutputCacheLocation.None, NoStore = true)]
        public PartialViewResult ManageModifiers(int id, int cpsId)
        {
            var model = VariantModel.GetVariantBoosts(id);
            ViewBag.cpsId = cpsId;
            return PartialView(model);
        }

        public PartialViewResult ViewDetails(int id)
        {
            var model = VariantModel.GetVariantDetails(id);
            return PartialView(model);
        }

        public PartialViewResult ViewRules(int id)
        {
            var model = VariantModel.GetVariantRules(id);
            return PartialView(model);
        }

        public PartialViewResult Header(int id)
        {
            var model = VariantModel.GetVariantDetails(id);
            return PartialView(model);
        }

        public PartialViewResult ViewTrends(int id)
        {
            var model = ReportingModel.GetTrendsVariantData(id);
            return PartialView("~/Views/Reporting/ViewTrends.cshtml", model);
        }

        [HttpGet]
        [OutputCache(Location = OutputCacheLocation.None, NoStore = true)]
        public PartialViewResult ManageDetails(int id, int cpsId)
        {
            var model = VariantModel.GetVariantDetails(id);
            ViewBag.cpsId = cpsId;
            return PartialView(model);
        }

        [HttpPost]
        public void ManageDetails(VariantDetails details)
        {
            // Save the variant Details
            VariantModel.UpdateVariantDetails(details);
        }

        [HttpPost]
        public void CreateVariant(VariantDetails details)
        {
            /********************************************************
             *      This method is used for the Modal Dialog POC    *
             ********************************************************/
            var Name = details.Name;
            var Description = details.Description;
            var Priority = details.Priority;
            var NumberOfAssets = details.NumberOfAssets;
        }

        [HttpPost]
        public JsonResult UpdateVariantAction(string variantList, string actionStatus, string experienceID)
        {
            switch (actionStatus)
            {
                case "Move Up":
                case "Move Down":
                    VariantModel.UpdateVariantListPriority(variantList, actionStatus);
                    break;
                default:
                    VariantModel.UpdateVariantStatus(variantList, actionStatus);
                    break;
            }

            // pass list back so we can rebind grid
            var m = ExperienceModel.GetExperienceStrategies(int.Parse(experienceID));
            return Json(new { strategies = m }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult VariantActionList()
        {
            var model = ModelBase.GetStatusList();
            model.Add("Move Up");
            model.Add("Move Down");
            return Json(model, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [OutputCache(Location = OutputCacheLocation.None, NoStore = true)]
        public PartialViewResult CreateRules(int NodeId, string updateTargetId)
        {
            var rm = new RuleViewModel() { VariantID = NodeId };

            ViewBag.UpdateTargetId = updateTargetId;
            return PartialView(rm);
        }

        [HttpPost]
        public JsonResult CreateRules(int variantID, int ruleID, string rulename)
        {
            if (ruleID <= 0)   // create
            {
                ruleID = RuleModel.CreateRule(variantID, rulename);
            }
            else
            {
                // TODO Update
            }

            return Json(new { id = ruleID, name = rulename });
        }

        [HttpPost]
        public JsonResult DeleteRules(int ruleID)
        {
            bool isDelete = RuleModel.DeleteRule(ruleID);
            if (isDelete)
                return Json("success");
            else
                return Json("Error");
        }

        [HttpGet]
        [OutputCache(Location = OutputCacheLocation.None, NoStore = true)]
        public PartialViewResult AddFilter(int variantID, string ruleName, int ruleID)
        {
            var vm = new ExpressionViewModel() { VariantID = variantID, RuleName = ruleName, RuleID = ruleID };
            return PartialView(vm);
        }

        [HttpGet]
        [OutputCache(Location = OutputCacheLocation.None, NoStore = true)]
        public PartialViewResult SelectAttribute(int ruleID)
        {
            ViewBag.ruleID = ruleID;
            return PartialView();
        }

        public JsonResult GetRuleOperators(string attributeType)
        {
            return Json(RuleModel.GetRuleOperators(attributeType), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetControlSet(string attributeType, string operatorType)
        {
            return Json(RuleModel.GetControlSet(attributeType, operatorType), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCatalogMappingFields(string ruleId)
        {
            return Json(RuleModel.GetCatalogMappingFields(System.Convert.ToInt32(ruleId)), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult SaveExpression(ExpressionViewModel expression)
        {
            int newId = RuleModel.SaveExpression(expression);
            return Json(new { id = newId });
            //return PartialView("ViewRules"); 
        }
    }
}

Resonance.Insight3.Web/Views/Variant/AddFilter.cshtml
@using System.Collections
@using Resonance.Insight3.Web.Helpers
@using Resonance.Insight3.Web.HtmlHelpers
@model Resonance.Insight3.Web.ViewModels.Rule.ExpressionViewModel
@{ 
    const string formName = "frmAddFilter";
    const string createContainer = "#insight-create-dialog2";
    string updateTargetId = ViewBag.UpdateTargetId; 
}
@using (Ajax.BeginForm("SaveExpression", "Variant",
    new AjaxOptions { HttpMethod = "Post", UpdateTargetId = @updateTargetId, OnSuccess = "onAjaxPostSuccess", OnFailure = "onAjaxPostFailure" }, new { id = @formName }))
{
    <div id='model-grey' class='greyedoutparentmodal'></div>     
    <div style="float: left; line-height:33px">
        <span>@Html.RequiredAsterik(this) @this.SharedResources("name")</span><img src="/Images/AssetTypes/Small/search.png" alt="" id="selectattribute"><br />
        @Html.TextBoxFor(m => m.Attribute, Model.Attribute)
        <br />
        @Html.HiddenFor(m => m.RuleID, Model.RuleID)
        @Html.HiddenFor(m => m.RuleName, Model.RuleName)
        @Html.HiddenFor(m => m.VariantID, Model.VariantID)
        @Html.HiddenFor(m => m.Operator, Model.Operator)
        @Html.Hidden("hdnAttribute")
    </div>    
    <div style="float: left;line-height:33px;padding-left:3px" id="divoperator">
        @this.SharedResources("operator")<br />
        <select id="ddlOperator" style="height: 25px;">
        </select>
        <br />
    </div>    
    <div style="float: left; line-height:33px;padding-left:3px" id="divcontextsoucre">
        @this.SharedResources("contextsource")<br />
        @Html.TextBoxFor(m => m.Context, Model.Context)
        <br />
    </div>
    <div style="float: left; line-height:33px;padding-left:3px" id="divvalues">
        @this.SharedResources("values")<br />
        @Html.TextBox("context")
        @*
           @(Html.Kendo().MultiSelect() // TODO: Multiselect for contexts
          .Name("optional")
          .Placeholder("Select Values")
          .BindTo(new List<string>() {
              "Item 1",
              "Item 2",
              "Item 3"
          })
        )*@
        <br />
    </div>
    <div style="float: left; line-height:33px;padding-left:3px" id="divdelta">
        @this.SharedResources("delta")<br />
        @Html.DropDownListFor(m => m.PlusOrMinus, @Model.PlusOrMinusList, new { @style = "height: 25px" })<br />
    </div>
    <div style="float: left; line-height:33px;padding-left:3px" id="divvalue">
        @this.SharedResources("value")<br />
        @Html.TextBoxFor(m => m.Value, Model.Value)
        <br />
    </div>
    <div style="float: left; line-height:33px;padding-left:3px" id="divType">
        @this.SharedResources("type")<br />
        @Html.DropDownListFor(m => m.PercentOrUnits, @Model.PercentOrUnitsList, new { @style = "height: 25px" })<br />
    </div>
    <div style="clear: both; text-align: right; margin-top: 10px">
        <input type="submit" class="insight-submit-btn" value="Save" id="btnAddFilter"/>&nbsp;
        <button onclick="cancelJqueryDialog('Rules', '@createContainer')" class="insight-cancel-btn" type="button" value="Cancel">Cancel</button>
    </div>
}
<script type="text/javascript">
    $(document).ready(function () {
        $("#divoperator").hide();
        hideallFields();
    });

    function hideallFields() {
        $("#divcontextsoucre").hide();
        $("#divdelta").hide();
        $("#divvalue").hide();
        $("#divType").hide();
        $("#divvalues").hide();
    }
    function onAjaxPostSuccess(response) {
        ShowsysMessage('success', 'Rule added successful');
        cancelJqueryDialogContinue('@createContainer');
    }

    function onAjaxPostFailure(response) {
        ShowsysMessage('error', 'An error occured during the save process');
    }

    $('#selectattribute').click(function (event) {
        var ruleID = $("#RuleID").val() == "" ? 0 : $("#RuleID").val();
        var data = {
            ruleID: ruleID
        };
        PopupJqueryMultiDialog("Select Attribute", "/Variant/SelectAttribute", data, "#insight-create-dialog3", true, '#insight-create-dialog2', event, 300, 300);
    });

    SetGrayedOutLayer();

    // TODO : Move this to common js file
    function SetGrayedOutLayer() {
        $('#insight-create-dialog2').closest('.ui-dialog').append('<div id="model-grey" class="greyedoutparentmodal"></div>');
    }

    function SetAtrribute1(e) {
        $("#Attribute").val(e.CatalogField);
        $("#hdnAttribute").val(e.AttributeType);
        onChange(e.AttributeType);
    }

    function onChange(attrType) {
        hideallFields();
        $("#divoperator").show();
        $('#ddlOperator').children().remove();
        $.ajax({
            url: '/Variant/GetRuleOperators',
            type: 'post',
            data: { attributeType: attrType },
            success: function (data) {
                $("#ddlOperator").get(0).options.length = 0;
                $("#ddlOperator").get(0).options[0] = new Option("---Select---", "-1");
                $.each(data, function (i, variant) {
                    $("#ddlOperator").append($('<option/>').text(variant.OperatorName).attr('value', variant.Operator));
                });
            },
            error: function () {
                alert('Error');
            }
        });
    }
    $("#ddlOperator").change(function (e) {
        hideallFields();
        var ddlOperatorText = $("#ddlOperator option:selected").text();
        if ($("#hdnAttribute").val() == "Currency" || $("#hdnAttribute").val() == "Continuous") {
            if (ddlOperatorText.toLowerCase().indexOf('relative') >= 0) {
                $("#divcontextsoucre").show();
                $("#divvalue").show();
                $("#divdelta").show();
                $("#divType").show();
            }
            else if (ddlOperatorText.toLowerCase() == "same as" || ddlOperatorText.toLowerCase() == "different from") {
                $("#divcontextsoucre").show();
            }
            else
                $("#divvalue").show();
        }
        else if (ddlOperatorText.toLowerCase() == "same as" || ddlOperatorText.toLowerCase() == "different from") {
            $("#divcontextsoucre").show();
        }
        else {
            $("#divvalues").show();
        }
        $("#Operator").val(ddlOperatorText);
        $.get('/Variant/GetControlSet', { "attributeType": $("#hdnAttribute").val(), operatorType: $("#ddlOperator").val() }, function (data) {
            if (data.AdditionalFields) {
                $("#divdelta").show();
                $("#divvalue").show();
                $("#divType").show();
            }
        });
    });
</script>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")"></script>

Resonance.Insight3.Web/Views/Variant/CreateRules.cshtml
@using System.Collections
@using Resonance.Insight3.Web.Helpers
@using Resonance.Insight3.Web.HtmlHelpers
@model Resonance.Insight3.Web.ViewModels.Rule.RuleViewModel
@{ 
    const string formName = "frmCreateRules";
    const string createContainer = "#insight-create-dialog";
    string updateTargetId = ViewBag.UpdateTargetId;
    
}

@using (Ajax.BeginForm("CreateRules", "Variant",
    new AjaxOptions { HttpMethod = "Post", UpdateTargetId = @updateTargetId, OnSuccess = "onAjaxPostSuccess", OnFailure = "onAjaxPostFailure" }, new { id = @formName }))
{
    @Html.HiddenFor(m => m.VariantID, Model.VariantID)
    @Html.Hidden("RuleID");
    <div>
        <fieldset>
            <legend>@Html.RadioButton("rbtnSelect", false, new { disabled = "disabled" })@this.SharedResources("ExistingRoleTitle")</legend>
        </fieldset>
    </div>
    <div style="margin-top: 10px">
        <fieldset>
            <legend>@Html.RadioButton("rbtnSelect", true, true)@this.SharedResources("NewRoleCreateTitle")</legend>
            <strong>@Html.RequiredAsterik(this) @this.SharedResources("name")</strong><br />
            @Html.TextBoxForWithDefault(m => m.Name, string.Empty, 200)<br />
            @Html.ValidationMessageFor(m => m.Name)<br />
            <br />
            <div class="k-widget k-grid" id="summarygrid">
                <table style="height: 100%; font-size: 0.9em;">
                    <thead class="k-grid-header">
                        <tr>
                            <th class="k-header" style="width: 40%"><a class="k-link" href="#">Summary</a></th>
                            <th class="k-header" style="width: 30%"><a class="k-link" href="#">Conditions</a></th>
                            <th class="k-header" style="width: 30%"><a class="k-link" href="#">Filters</a></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td style="min-height: 40px">This strategy will return results ...</td>
                            <td>
                                <div id="addCondition">
                                    <img id="imgAddCondition" alt="Add Condition" src="~/Images/add-green.png" />&nbsp;Add Condition
                                </div>
                            </td>
                            <td>
                                <div id="addFilter">
                                    <img id="imgAddFilter" alt="Add Filter" src="~/Images/add-green.png" />&nbsp;Add Filter
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </fieldset>
    </div>
    <div style="clear: both; text-align: right; margin-top: 10px">
        <input type="submit" class="insight-submit-btn" value="Save" id="btnCreateRule" disabled="disabled" />&nbsp;
        <button onclick="deleteRule();" class="insight-cancel-btn" type="button" value="Cancel" id="cancel">Cancel</button>
    </div>
}
<script type="text/javascript">
    function onAjaxPostSuccess(response) {
        ShowsysMessage('success', 'Rule added successful');
        cancelJqueryDialogContinue('@createContainer');
    }

    function onAjaxPostFailure(response) {
        ShowsysMessage('error', 'An error occured during the save process');
    }
    $("#addCondition").hide();
    $("#addFilter").hide();

    // TODO Save Method 
    $("#Name").bind("blur", function (e) {
        var rulename = $("#Name").val();
        var variantID = $("#VariantID").val();
        if (rulename != "") {
            $("#addCondition").show();
            $("#addFilter").show();
            $.post('/Variant/CreateRules', { "variantID": variantID, "ruleID": $("#RuleID").val() == "" ? 0 : $("#RuleID").val(), "rulename": rulename }, function (data) {
                $("#RuleID").val(data.id);
            });
        }
        else {
            $("#addCondition").hide();
            $("#addFilter").hide();
        }
    });

    $('#@formName :input').change(function () { toggleSaveButton('@formName'); });
    $('#@formName :input').on('keypress', function () { toggleSaveButton('@formName'); });

    $('#imgAddFilter').click(function (event) {
        var rulename = $("#Name").val();
        var variantID = $("#VariantID").val();
        var ruleID = $("#RuleID").val() == "" ? 0 : $("#RuleID").val();
        var data = {
            variantID: variantID,
            ruleName: rulename,
            ruleID: ruleID
        };
        PopupJqueryMultiDialog("Add Filter", "/Variant/AddFilter", data, "#insight-create-dialog2", true, '#insight-create-dialog', event, 750, 400);
    });

    $('#imgAddCondition').click(function (event) {
        alert('In progress');
        //PopupJqueryMultiDialog("Add Condition", "Variant/AddCondition", false, "#insight-create-dialog2", true, event);
    });

    SetGrayedOutLayer();

    // TODO : Move this to common js file
    function SetGrayedOutLayer() {
        $('#insight-create-dialog').closest('.ui-dialog').append('<div id="model-grey" class="greyedoutparentmodal"></div>');
    }

    function deleteRule() {
        $.post('/Variant/DeleteRules', { "ruleID": $("#RuleID").val() }, function (data) {
            cancelJqueryDialog('Rules', '@createContainer');
        });
    }
</script>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")"></script>

Resonance.Insight3.Web/Views/Variant/Header.cshtml
@model Resonance.Insight3.Web.ViewModels.Variant.VariantDetails

<div style="border-bottom: solid 1px #000; padding: 6px 5px 2px 5px;">
    <span style="font-size: 130%;">@Model.Name</span> - Strategy
</div>

Resonance.Insight3.Web/Views/Variant/ViewRules.cshtml
@using Resonance.Insight3.Web.Helpers
@model List<Resonance.Insight3.Web.ViewModels.Variant.VariantRule>

<div id="divVariantRules">
@if (Model != null && Model.Count > 0)
{
    @(Html.Kendo().Grid(Model)
          .Name("VariantRules")
          .Columns(columns =>
                       {
                           columns.Bound(p => p.RuleID).Hidden(true);
                           columns.Bound(p => p.Name).Width(250).HtmlAttributes(new {@style="vertical-align: top"});
                           columns.Bound(p => p.RuleText).Encoded(false).Title("This strategy will return results");
                       })
          .TableHtmlAttributes(new {style="font-size:0.9em;"})
          .Sortable()                       
          .DataSource(dataSource => dataSource
                                        .Ajax()
                                        .ServerOperation(false)
          ))
}
else
{
    <span><span class="bold"><i>No Rules Configured</i></span></span>
}
</div>  

<script type="text/javascript">
    var c = '@Model.Count';
    $.each($('#Rules_TitleBar').find('.toggleAddEdit'), function (i, val) {
        val = $(val);
        if ($(val).attr('data-create-url')) {
            if (c > 0) {
                $(val).css('display', 'none');
            }
        }
        else {
            if (c == 0) {
                $(val).css('display', 'none');
            }
        }
    });
</script> 